sudo: required
language: bash
services:
  - docker
install: 
  - docker build -t keboola/docker-custom-r .
script:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
